### ISSUE TITLE
MagmaHackers Assignment 2 review

### ISSUE THREAD

**Issue by ulisesac4** [Balthair94/MHAssignment01#1]
Hi Baltazar! let me write my review now:

**Code review**
I am not going to talk about indentation and all of that, because at the end minifing this files is the way to go on the deploying stage with some tools to automate this task. Your code and hierarchies are ok and I do not have anything to address but in the other hand I have something to say:

1. Code that perform nothing: In your skills' section you have your images with icons representing that skill, but you do not have an alt for each image, that is not an issue at all because we are not forced to have an alt, but you have its empty label in your code so it is unnecessary and its loading bulk (at this rate some chars will not make a difference in file size but imagine if this slips into bigger projects).

2. Unnecessary code: In your javascript file your function moveTo may have no real purpose because if you do not set the 'smooth' option your scrollIntoView performs the same action than a raw href="#yourId", so I would set that option to true or remove it completely. 

**Design review**
Overall I like the design of your page, I like the color palette and find helpful the images that you are using, but I have concerns with some points that I like to address: 

1.  Having many javascript files: Lets be honest, having the necessary files is ok and having separated are ok but in this case I do not find useful to have 2 files for this task. Checking the functions we can agree that everyone serves the purpose to improve the UX so I believe this encourages this opinion.

2. Not having a real footer: You are using the footer tag in your file and that is ok, but the html rendered does not shows this behavior, seeing your page we can think that your name sloped to the bottom or that you did not finished, so you should at last add a color to your footer to make it more appealing.

3. Not being enough explicit: I believe that your project's section does not show a clue that it is an extensible widget, so I would change that section for another structure like a grid or cards. Also your hobbies does not show enough info, for example in the cartoons part I got confused that if you only like Samurai Jack or the general, but also this do not take all serious I may be to salty in this, but your project's sections needs an improvement hahaha.

Well that is all, if you have something to address say it please, you are not the only one getting better with this exercise :), thank you I am waiting your review in my project.

**Comment by Balthair94** [comment]
Hi Ulises.

I implemented all your issues. I hope it cold looks more decent.

Good day.
