### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by ozmar-11** [Balthair94/MHAssignment01#2]
Configure your text editor or development environment to use 2 spaces per tab, the is most common  2 spaces per tab and also some marked languages like YAML may cause errors if yo don't print 2 spaces per tab also, try that your lines be maximum 80 characters of length

**Comment by Balthair94** [comment]
I am not sure what are you talking about.

**Comment by ozmar-11** [comment]
when you press tab your text editor print 4 blank spaces, the convention is print just 2 blank spaces per tab
