### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by aldompe95** [Balthair94/MHAssignment01#3]
Hi i have a doubt here:
```
$('.avatar-container').on('click',function(){
  if ($(this).find('.info').length <= 0) {
    $(this).append('<div class="info"><div class="info-inner"></div></div>');
  }
  var $info = $(this).find('.info'),
      $inner= $(this).find('.info-inner'),
      $p    = $(this).attr("class").match(/p-\w+/).toString().substring(2);
      console.log($p);
  $inner.text($p+'%');
  $info.toggleClass('js-active');
});
```
it cost me to understand the regexp, its something relative new for me, but why dont you just put the html under the `<img>` tag like ``` <div class="info"><div class="info-inner">65%</div></div> ``` and then you just make this js
```
$('.avatar-container').on('click',function(){	
  $info = $(this).find('.info');
  $info.toggleClass('js-active');
});
```

**Comment by Balthair94** [comment]
That is to create the div over the image that contains the porcentage text. It checks if the div is already there then I (or the owner of the code) remove the elements.
I think that is better on this way because I don't have to add html code that is going to be hide.

**Comment by aldompe95** [comment]
Well if you dont want to put the html you can do something like this:
 
 *Use data attributes

  `<div class="avatar-container" data-percent="61%">`

   and this js:
```
$('.avatar-container').hover(function(){
  var percent = $(this).data("percent");
  if ($(this).find('.info').length <= 0) {
    $(this).append('<div class="info"><div class="info-inner">'+percent+'</div></div>');
  }
  var $info = $(this).find('.info');
  $info.toggleClass('js-active');
});
```
I think theres no need to make it more complex like a regex function to just show a div, and this way its more readable i guess
