### ISSUE TITLE
Monochrome

### ISSUE THREAD

**Issue by tzohpilotl** [Balthair94/MHAssignment01#4]
Baltazar, how are you? I just had an appreciation moment in your page and what I liked the most was your story about why you like computing. It would be really nice if you add some more shades of gray to your page or some other colors to enhance it's appearance. Your projects seem interesting especially the masseges one ;). Have a nice one, friend!

**Comment by Balthair94** [comment]
Do you have any suggestion about which colors can I include and where? and also for the shades.

**Comment by tzohpilotl** [comment]
I use pages like these http://www.color-hex.com/. They give you shades, tints, analogous colors, it's complement, it's triadic colors; all of those can be used in a page, specially the triadic.
