### ISSUE TITLE
My review

### ISSUE THREAD

**Issue by diegosaul402** [Balthair94/MHAssignment01#5]
Hi Baltazar,
You do a good work on your page, can't say much about. Looks good, maybe except of that green as background, I don't think combines with your page.
Maybe you could write more about your projects.
Your code looks good, maybe you could use just divs instead of tables (a lot of people on internet says this, as new I don't know why xD).
Good job.

**Comment by Balthair94** [comment]
Ok. Thanks for the recommendations. But the green is from the image and it was the only one that I felt that represent Android. 
Next time i will include divs instead of tables. This time i wanted it to use them because y want to see the style that bootstrap has for them.
