### ISSUE TITLE
Nav-bar and footer

### ISSUE THREAD

**Issue by salvadorJimenez** [Balthair94/MHAssignment01#6]
Excellent job baltazar, the content of your page reflect your personality and you are clear with the things that you like and your skills, so i have a few things to say.

First- when i see your web page in my phone the nav bar obstruct with the content so that means that is not responsive, maybe you know that but it's just a comment.

Next - the footer don't have useful information, just your name, so maybe you can't put there your information of contact or something like that.

Also the content of your hobbies is not responsive when i see it in my phone the images and titles are mixed and it's not understandable.

So about your code,i don't have too much to say is good so good job. :D

**Comment by Balthair94** [comment]
I included the contact information. About the responsive part i will include that in my next works, but that still being an eavy topic for me... and i dont have much time, but i will do my best the next time.
